// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOnRHrsy_hT0vnDqBZQRvmSdG8pjfFrwU',
    appId: '1:514838871492:ios:13a67ac322817a01a53891',
    messagingSenderId: '514838871492',
    projectId: 'smartcafemanager-a8231',
    storageBucket: 'smartcafemanager-a8231.firebasestorage.app',
    iosBundleId: 'com.example.smartCafeManager',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMt5dfWinZtM-_Uw-WW_YLnZxe5v_Irso',
    appId: '1:514838871492:web:3dc883a946a41468a53891',
    messagingSenderId: '514838871492',
    projectId: 'smartcafemanager-a8231',
    authDomain: 'smartcafemanager-a8231.firebaseapp.com',
    storageBucket: 'smartcafemanager-a8231.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOnRHrsy_hT0vnDqBZQRvmSdG8pjfFrwU',
    appId: '1:514838871492:ios:13a67ac322817a01a53891',
    messagingSenderId: '514838871492',
    projectId: 'smartcafemanager-a8231',
    storageBucket: 'smartcafemanager-a8231.firebasestorage.app',
    iosBundleId: 'com.example.smartCafeManager',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAFBxM0xWyusY15phAwPUcnj5Oy675PNA',
    appId: '1:514838871492:android:700179cb1bf12c6ca53891',
    messagingSenderId: '514838871492',
    projectId: 'smartcafemanager-a8231',
    storageBucket: 'smartcafemanager-a8231.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMt5dfWinZtM-_Uw-WW_YLnZxe5v_Irso',
    appId: '1:514838871492:web:22918cde93d353f7a53891',
    messagingSenderId: '514838871492',
    projectId: 'smartcafemanager-a8231',
    authDomain: 'smartcafemanager-a8231.firebaseapp.com',
    storageBucket: 'smartcafemanager-a8231.firebasestorage.app',
  );

}